### ISSUE TITLE
First README link broken

### ISSUE THREAD

**Issue by mgattozzi** [rust-community/rust-lang-blog-boilerplate#1]
Currently the link points to -> https://o0ignition0o.github.io/rust-lang-blog-boilerplate/
but I don't think it's hosted there anymore and is instead here -> https://blog.jeremylempereur.com/
but was too unsure to actually open a PR to fix it.

**Comment by o0Ignition0o** [comment]
Hi @mgattozzi and thanks for raising the issue !
I will write a list of steps to fix it and mark it as an easy pull request, hopefully someone will use it as a nice first contribution :)

**Comment by o0Ignition0o** [comment]
Ok here are the steps to fix this : 

Go to the README.md file

At line 6, change the url from

> `https://o0ignition0o.github.io/rust-lang-blog-boilerplate/`

 to 

> `https://github.com/rust-community/rust-lang-blog-boilerplate/`

Bonus points: Find other occurrences of the old github repository, and edit them if necessary.

If anyone wants to try to tackle it, please let me know and I'll help you along the way :)

**Comment by callym** [comment]
I was going to fix this but I'm not sure what URL to change it to?
@mgattozzi says https://blog.jeremylempereur.com/
@o0Ignition0o says https://github.com/rust-community/rust-lang-blog-boilerplate/
I'm assuming it should be the first one as the second is just a link to this repo?
Maybe the boilerplate demo should be hosted on a `rust-community` Github Page?

**Comment by o0Ignition0o** [comment]
Hi @callym and thanks for jumping in ! :)

After reading it a bit, it turns out @mgattozzi is right. But since the repository has been transfered to the rust-community, we might be able to change the sentence to reflect a more general Rust lang blog : 

> This is the code that powers the rustlang blog boilerplate. 

Could probably be something else instead, like :  

> This is the boilerplate code which will allow you to power your blog, looking like [The rust lang blog](https://blog.rust-lang.org/).

How do you feel about this change? Does it seem correct to you ?

**Comment by callym** [comment]
That sounds like a good change! 😄
